import { describe, expect, it } from "vitest";

import {
  ArtifactEvent,
  ErrorEvent,
  LogEvent,
  parseRecipeEvent,
  RecipeEvent,
  ResultEvent,
  StepEvent,
  ToolCallEvent,
  TokenEvent,
} from "@/lib/execution/events";

/**
 * Fixtures below are the REAL, verbatim `model_dump_json()` output of
 * `../backend/src/skillet/recipe/events.py`'s 7 event models, generated by
 * running (from `backend/`):
 *
 *   uv run python -c "
 *   from skillet.recipe.events import StepEvent, TokenEvent, ToolCallEvent, LogEvent, ArtifactEvent, ResultEvent, ErrorEvent
 *   print(StepEvent(id='s1', name='Thinking', status='start', ts=0.1).model_dump_json())
 *   print(StepEvent(id='s1', name='Thinking', status='finish', detail='done', ts=0.2).model_dump_json())
 *   print(TokenEvent(text='hello').model_dump_json())
 *   print(ToolCallEvent(id='t1', name='search', args={'q':'x'}, result={'n':1}, ts=0.2).model_dump_json())
 *   print(LogEvent(level='info', message='hi', ts=0.3).model_dump_json())
 *   print(ArtifactEvent(id='a1', kind='json', name='out', data={'x':1}).model_dump_json())
 *   print(ArtifactEvent(id='a2', kind='file', name='report.csv', url='/tmp/x.csv').model_dump_json())
 *   print(ResultEvent(data={'ok': True}, ts=1.0).model_dump_json())
 *   print(ErrorEvent(error_type='timeout', message='boom', recoverable=False, ts=1.1).model_dump_json())
 *   "
 *
 * which printed (one JSON string per line, pasted verbatim as object literals):
 *   {"type":"step","id":"s1","name":"Thinking","status":"start","detail":null,"ts":0.1}
 *   {"type":"step","id":"s1","name":"Thinking","status":"finish","detail":"done","ts":0.2}
 *   {"type":"token","text":"hello"}
 *   {"type":"tool_call","id":"t1","name":"search","args":{"q":"x"},"result":{"n":1},"ts":0.2}
 *   {"type":"log","level":"info","message":"hi","ts":0.3}
 *   {"type":"artifact","id":"a1","kind":"json","name":"out","data":{"x":1},"url":null}
 *   {"type":"artifact","id":"a2","kind":"file","name":"report.csv","data":null,"url":"/tmp/x.csv"}
 *   {"type":"result","data":{"ok":true},"ts":1.0}
 *   {"type":"error","error_type":"timeout","message":"boom","recoverable":false,"ts":1.1}
 *
 * Note the wire format is plain snake_case — NO camelCase conversion,
 * unlike every other backend model this frontend consumes.
 */

const STEP_START = { type: "step", id: "s1", name: "Thinking", status: "start", detail: null, ts: 0.1 };
const STEP_FINISH = {
  type: "step",
  id: "s1",
  name: "Thinking",
  status: "finish",
  detail: "done",
  ts: 0.2,
};
const TOKEN = { type: "token", text: "hello" };
const TOOL_CALL = {
  type: "tool_call",
  id: "t1",
  name: "search",
  args: { q: "x" },
  result: { n: 1 },
  ts: 0.2,
};
const LOG = { type: "log", level: "info", message: "hi", ts: 0.3 };
const ARTIFACT_JSON = {
  type: "artifact",
  id: "a1",
  kind: "json",
  name: "out",
  data: { x: 1 },
  url: null,
};
const ARTIFACT_FILE = {
  type: "artifact",
  id: "a2",
  kind: "file",
  name: "report.csv",
  data: null,
  url: "/tmp/x.csv",
};
const RESULT = { type: "result", data: { ok: true }, ts: 1.0 };
const ERROR = { type: "error", error_type: "timeout", message: "boom", recoverable: false, ts: 1.1 };

describe("StepEvent", () => {
  it("parses a start event", () => {
    expect(StepEvent.parse(STEP_START)).toEqual(STEP_START);
  });

  it("parses a finish event with a detail string", () => {
    expect(StepEvent.parse(STEP_FINISH)).toEqual(STEP_FINISH);
  });

  it("rejects a status outside start/finish/error", () => {
    expect(() => StepEvent.parse({ ...STEP_START, status: "pending" })).toThrow();
  });
});

describe("TokenEvent", () => {
  it("parses a token event", () => {
    expect(TokenEvent.parse(TOKEN)).toEqual(TOKEN);
  });
});

describe("ToolCallEvent", () => {
  it("parses a tool_call event with arbitrary args/result shapes", () => {
    expect(ToolCallEvent.parse(TOOL_CALL)).toEqual(TOOL_CALL);
  });
});

describe("LogEvent", () => {
  it("parses a log event", () => {
    expect(LogEvent.parse(LOG)).toEqual(LOG);
  });
});

describe("ArtifactEvent", () => {
  it("parses a json-kind artifact event (url null)", () => {
    expect(ArtifactEvent.parse(ARTIFACT_JSON)).toEqual(ARTIFACT_JSON);
  });

  it("parses a file-kind artifact event (data null)", () => {
    expect(ArtifactEvent.parse(ARTIFACT_FILE)).toEqual(ARTIFACT_FILE);
  });
});

describe("ResultEvent", () => {
  it("parses a result event", () => {
    expect(ResultEvent.parse(RESULT)).toEqual(RESULT);
  });
});

describe("ErrorEvent", () => {
  it("parses an error event", () => {
    expect(ErrorEvent.parse(ERROR)).toEqual(ERROR);
  });

  it("rejects an error_type outside the 5 known values", () => {
    expect(() => ErrorEvent.parse({ ...ERROR, error_type: "network_error" })).toThrow();
  });
});

describe("RecipeEvent (discriminated union)", () => {
  it.each([
    ["step (start)", STEP_START],
    ["step (finish)", STEP_FINISH],
    ["token", TOKEN],
    ["tool_call", TOOL_CALL],
    ["log", LOG],
    ["artifact (json)", ARTIFACT_JSON],
    ["artifact (file)", ARTIFACT_FILE],
    ["result", RESULT],
    ["error", ERROR],
  ])("routes %s to its matching schema", (_label, raw) => {
    expect(RecipeEvent.parse(raw)).toEqual(raw);
  });

  it("rejects an event missing its type field", () => {
    const withoutType: Record<string, unknown> = { ...TOKEN };
    delete withoutType.type;
    expect(() => RecipeEvent.parse(withoutType)).toThrow();
  });

  it("rejects an event with an unknown type", () => {
    expect(() => RecipeEvent.parse({ ...TOKEN, type: "unknown_event" })).toThrow();
  });
});

describe("parseRecipeEvent", () => {
  it("parses valid raw input the same as RecipeEvent.parse", () => {
    expect(parseRecipeEvent(RESULT)).toEqual(RESULT);
  });

  it("throws on invalid raw input", () => {
    expect(() => parseRecipeEvent({ type: "nope" })).toThrow();
  });
});
